export { QRAuth } from './client.js';
export { ALG_VERSIONS, isAlgDeprecated } from './types.js';
export type {
  QRAuthOptions,
  CreateQRCodeOptions,
  QRCodeResponse,
  ListQRCodesOptions,
  QRCodeDetail,
  PaginatedResponse,
  VerifyOptions,
  VerificationResult,
  VerificationWarning,
  AlgVersion,
  AlgVersionStatus,
  BulkCreateItem,
  BulkCreateResponse,
  DomainWarning,
  CreateAuthSessionOptions,
  AuthSessionResponse,
  AuthSessionUser,
  AuthSessionStatus,
  GetAuthSessionOptions,
  AuthSessionVerifyResult,
  CreateEphemeralSessionOptions,
  EphemeralSessionResponse,
  ClaimEphemeralSessionOptions,
  EphemeralSessionClaimResult,
  ListEphemeralSessionsOptions,
  EphemeralSessionDetail,
  ProximityAttestationOptions,
  ProximityAttestationResult,
  ProximityVerifyOptions,
  ProximityVerifyResult,
} from './types.js';
export {
  QRAuthError,
  AuthenticationError,
  AuthorizationError,
  NotFoundError,
  RateLimitError,
  QuotaExceededError,
  ValidationError,
} from './errors.js';
