import { randomBytes } from 'node:crypto';
import type { OidcRefreshToken, PrismaClient } from '@prisma/client';
import { hashString } from './crypto.js';

/**
 * OIDC refresh-token helpers (ADR-0003 Slice 5).
 *
 * Refresh tokens are opaque 32-byte random values, stored only as their
 * SHA-256 hash (`OidcRefreshToken.tokenHash`, unique-indexed — same posture as
 * auth codes / access tokens). Every token in one authorization grant shares a
 * `familyId`; rotation chains the rows via `replacedById`, and reuse detection
 * revokes the whole family.
 *
 * AUDIT-FINDING-012: all lookups go through Prisma `where: { tokenHash }`
 * (constant-time unique-index lookup) — never a bare `===` on the hash.
 *
 * Pure except for the injected Prisma client; no clock injection (issuance/
 * rotation/revocation all stamp the wall clock, which is correct for tokens).
 */

/** Default refresh-token lifetime: 14 days. */
export const DEFAULT_REFRESH_TTL_SECONDS = 1_209_600;

/**
 * Mint a fresh refresh token and insert its `OidcRefreshToken` row.
 *
 * `familyId` is omitted for initial issuance (a new family id is generated) and
 * provided for rotation (the successor inherits its predecessor's family). The
 * row `id` is generated by Prisma (`@default(cuid())`) and returned as `rowId`
 * so the caller can set `replacedById` on the parent during rotation.
 */
export async function mintRefreshToken(args: {
  prisma: PrismaClient;
  familyId?: string;
  oidcClientId: string;
  userId: string;
  scope: string;
  ttlSeconds?: number;
  /**
   * Original end-user authentication time (OIDC Core §12.2). Stored so every
   * ID token minted from this family — initial and all rotations — echoes the
   * same `auth_time`. Omitted only for legacy callers; null rows fall back to
   * the family-root `createdAt` approximation at refresh time.
   */
  authTime?: Date | null;
}): Promise<{ token: string; rowId: string; familyId: string; expiresAt: Date }> {
  const ttlSeconds = args.ttlSeconds ?? DEFAULT_REFRESH_TTL_SECONDS;
  // Family id style matches the dashboard refresh-token family (lib/refresh-token.ts).
  const familyId = args.familyId ?? randomBytes(16).toString('hex');
  const token = randomBytes(32).toString('base64url');
  const expiresAt = new Date(Date.now() + ttlSeconds * 1000);

  const row = await args.prisma.oidcRefreshToken.create({
    data: {
      tokenHash: hashString(token),
      familyId,
      oidcClientId: args.oidcClientId,
      userId: args.userId,
      scope: args.scope,
      expiresAt,
      authTime: args.authTime ?? null,
    },
    select: { id: true },
  });

  return { token, rowId: row.id, familyId, expiresAt };
}

/**
 * Atomic rotation claim: mark the presented token as rotated (`rotatedAt` +
 * `replacedById`) iff it has not been rotated yet. Mirrors the auth-code
 * single-use claim (`WHERE … rotatedAt IS NULL` + count check) so two
 * concurrent rotations of the same token cannot both win.
 *
 * Returns the now-rotated row when exactly one was claimed; `null` when zero
 * rows were updated (token doesn't exist OR was already rotated — the caller
 * disambiguates via a prior existence/expiry/revocation check).
 */
export async function claimRefreshToken(args: {
  prisma: PrismaClient;
  tokenHash: string;
  successorRowId: string;
}): Promise<OidcRefreshToken | null> {
  const claim = await args.prisma.oidcRefreshToken.updateMany({
    where: { tokenHash: args.tokenHash, rotatedAt: null },
    data: { rotatedAt: new Date(), replacedById: args.successorRowId },
  });
  if (claim.count === 0) return null;
  return args.prisma.oidcRefreshToken.findUnique({ where: { tokenHash: args.tokenHash } });
}

/**
 * Revoke every still-active token in a family (OAuth 2.1 §6.1 reuse response).
 * Idempotent — only flips rows whose `revokedAt` is still null. Returns the
 * number of rows revoked (the caller logs it as a security signal).
 */
export async function invalidateFamily(args: {
  prisma: PrismaClient;
  familyId: string;
}): Promise<number> {
  const res = await args.prisma.oidcRefreshToken.updateMany({
    where: { familyId: args.familyId, revokedAt: null },
    data: { revokedAt: new Date() },
  });
  return res.count;
}
