// Utility to export QR codes in various formats: SVG, PNG, JPEG, PDF, and print

/**
 * Gets the SVG element from a container
 */
function getSvgFromContainer(container: HTMLElement): SVGSVGElement | null {
  return container.querySelector('svg');
}

/**
 * Renders just the SVG QR code to a canvas (more reliable than foreignObject)
 */
function renderSvgToCanvas(
  svgEl: SVGSVGElement,
  width: number,
  height: number,
  scale: number = 4,
  bgColor: string = '#FFFFFF'
): Promise<HTMLCanvasElement> {
  return new Promise((resolve, reject) => {
    const canvas = document.createElement('canvas');
    canvas.width = width * scale;
    canvas.height = height * scale;
    const ctx = canvas.getContext('2d')!;
    ctx.scale(scale, scale);

    // Background
    ctx.fillStyle = bgColor;
    ctx.fillRect(0, 0, width, height);

    const svgData = new XMLSerializer().serializeToString(svgEl);
    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);
    const img = new Image();
    img.onload = () => {
      ctx.drawImage(img, 0, 0, width, height);
      URL.revokeObjectURL(url);
      resolve(canvas);
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('SVG render failed'));
    };
    img.src = url;
  });
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---- Public API ----

export async function exportAsSVG(container: HTMLElement, filename: string) {
  const svg = getSvgFromContainer(container);
  if (!svg) throw new Error('No SVG found');
  const svgData = new XMLSerializer().serializeToString(svg);
  const blob = new Blob([svgData], { type: 'image/svg+xml' });
  downloadBlob(blob, `${filename}.svg`);
}

export async function exportAsPNG(
  container: HTMLElement,
  filename: string,
  bgColor: string = '#FFFFFF',
  size: number = 1024
) {
  const svg = getSvgFromContainer(container);
  if (!svg) throw new Error('No SVG found');
  const canvas = await renderSvgToCanvas(svg, size, size, 1, bgColor);
  canvas.toBlob((blob) => {
    if (blob) downloadBlob(blob, `${filename}.png`);
  }, 'image/png');
}

export async function exportAsJPEG(
  container: HTMLElement,
  filename: string,
  bgColor: string = '#FFFFFF',
  size: number = 1024
) {
  const svg = getSvgFromContainer(container);
  if (!svg) throw new Error('No SVG found');
  const canvas = await renderSvgToCanvas(svg, size, size, 1, bgColor);
  canvas.toBlob(
    (blob) => {
      if (blob) downloadBlob(blob, `${filename}.jpg`);
    },
    'image/jpeg',
    0.95
  );
}

export async function exportAsWebP(
  container: HTMLElement,
  filename: string,
  bgColor: string = '#FFFFFF',
  size: number = 1024
) {
  const svg = getSvgFromContainer(container);
  if (!svg) throw new Error('No SVG found');
  const canvas = await renderSvgToCanvas(svg, size, size, 1, bgColor);
  canvas.toBlob(
    (blob) => {
      if (blob) downloadBlob(blob, `${filename}.webp`);
    },
    'image/webp',
    0.95
  );
}

export async function exportAsPDF(
  container: HTMLElement,
  filename: string,
  bgColor: string = '#FFFFFF',
  captionText?: string,
  token?: string
) {
  const svg = getSvgFromContainer(container);
  if (!svg) throw new Error('No SVG found');
  const canvas = await renderSvgToCanvas(svg, 400, 400, 3, bgColor);
  const imgData = canvas.toDataURL('image/png');

  const printWindow = window.open('', '_blank');
  if (!printWindow) throw new Error('Popup blocked');

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>QRAuth - ${token || filename}</title>
      <style>
        @page { size: A4; margin: 20mm; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; text-align: center; padding-top: 40px; }
        .qr-img { width: 300px; height: 300px; }
        .token { font-family: monospace; font-size: 24px; font-weight: bold; letter-spacing: 3px; margin-top: 16px; }
        .caption { color: #666; font-size: 14px; margin-top: 8px; }
        .footer { margin-top: 40px; color: #999; font-size: 11px; border-top: 1px solid #eee; padding-top: 16px; }
      </style>
    </head>
    <body>
      <img class="qr-img" src="${imgData}" />
            ${captionText ? `<div class="caption">${captionText}</div>` : ''}
      <div class="footer">Generated by QRAuth — Verified QR Code Security Platform</div>
      <script>window.onload = function() { window.print(); }</script>
    </body>
    </html>
  `);
  printWindow.document.close();
}

export async function printQR(
  container: HTMLElement,
  bgColor: string = '#FFFFFF',
  captionText?: string,
  token?: string
) {
  const svg = getSvgFromContainer(container);
  if (!svg) throw new Error('No SVG found');
  const canvas = await renderSvgToCanvas(svg, 400, 400, 3, bgColor);
  const imgData = canvas.toDataURL('image/png');

  const printWindow = window.open('', '_blank');
  if (!printWindow) throw new Error('Popup blocked');

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>Print QRAuth Code</title>
      <style>
        @page { margin: 10mm; }
        body { text-align: center; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; }
        .qr-img { width: 280px; height: 280px; margin-top: 20px; }
        .token { font-family: monospace; font-size: 22px; font-weight: bold; letter-spacing: 3px; margin-top: 12px; }
        .caption { color: #666; font-size: 13px; margin-top: 6px; }
      </style>
    </head>
    <body>
      <img class="qr-img" src="${imgData}" />
            ${captionText ? `<div class="caption">${captionText}</div>` : ''}
      <script>
        window.onload = function() {
          setTimeout(function() { window.print(); window.close(); }, 300);
        };
      </script>
    </body>
    </html>
  `);
  printWindow.document.close();
}
